// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace OlxDataAccess.Models
{
    [Table("Chat_Message")]
    [Index("Chat_Id", Name = "IX_Chat_Message_Chat_Id")]
    public partial class Chat_Message
    {
        [Key]
        public int Id { get; set; }
        public int Chat_Id { get; set; }
        [Required]
        public string Message { get; set; }
        [Column(TypeName = "date")]
        public DateTime Date { get; set; }
        public TimeSpan Time { get; set; }

        [ForeignKey("Chat_Id")]
        [InverseProperty("Chat_Messages")]
        public virtual Chat Chat { get; set; }
    }
}