// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace OlxDataAccess.Models
{
    [Table("Chat")]
    [Index("Sender_ID", Name = "IX_Chat_User_One")]
    [Index("Receiver_ID", Name = "IX_Chat_User_Two")]
    public partial class Chat
    {
        [Key]
        public int Id { get; set; }
        public int Sender_ID { get; set; }
        public int Receiver_ID { get; set; }
        public bool? Block { get; set; }
    }
}