// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace OlxDataAccess.Models
{
    [Table("Company")]
    [Index("OwnerID", Name = "IX_Company_OwnerID")]
    public partial class Company
    {
        [Key]
        public int Id { get; set; }
        public string Logo_Url { get; set; }
        public string Cover_Url { get; set; }
        [StringLength(50)]
        public string Tax_Number { get; set; }
        public int? Owner { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Register_Date { get; set; }
        public int OwnerID { get; set; }

        [ForeignKey("OwnerID")]
        [InverseProperty("Companies")]
        public virtual User OwnerNavigation { get; set; }
    }
}