// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace OlxDataAccess.Models
{
    [Table("User_Connection")]
    public partial class User_Connection
    {
        [Key]
        public int User_ID { get; set; }
        [Key]
        [StringLength(50)]
        public string Connection_ID { get; set; }

        [ForeignKey("User_ID")]
        [InverseProperty("User_Connections")]
        public virtual User User { get; set; }
    }
}